### ISSUE TITLE
New events don't show up right after being added

### ISSUE THREAD

**Issue by Addisonbean** [INOVA-Technology/Koolendar#1]
You have to go back to the month view, then back to the day view to see an event you just added.

**Comment by ChaseWeimer** [comment]
I think I know why.... I cant fix it right now tho.  I think the issue is that the list has already been rendered so it doesnt re process it until it goes back to a view that was b4 it.  I believe this is a con to using storyboards.  Heres a fancy little diagram to explain my theory.

this is how we have it set up in the storyboard:
 ---MonthView---   ->  ---List of Events---  ->  ---Add Event---

I think its basically archiving the previous view.  Is there a way to refresh the view somehow?

**Comment by Addisonbean** [comment]
Well there's some kind of tableView.refreshData thing but I forget how to do that

**Comment by ChaseWeimer** [comment]
:D I think ive nearly got it!

**Comment by ChaseWeimer** [comment]
Looks like theres a clean up on isle 5
-Michael Scott

**Comment by Addisonbean** [comment]
Hahaha
